### PR TITLE
Clap functionality

### PR DESCRIPTION
**Pull request by Dynasto**
Type /clap to get the clapping emoji! This is my first pull request, please take action if it's broken or something.

### CODE REVIEW

**Comment by mcicoria** [comment]
I added this to single-string, but merged anyway. Definitely works. 👍

**Comment by Dynasto** [comment]
Oh that's very true. As I said this is my first time doing this but I'll keep that in mind in the future! :)

On a sidenote, it said in the files that I should test it locally first, but I'm not really sure on how to do that. Could someone explain? I just ctrlc ctrlv all my code into the console window of a site and saw what happened, but is there another way?

**Comment by Dynasto** [comment]
@vmednis @mcicoria could you please answer my question above if you can? :) Or is there another forum for general questions?

**Comment by mcicoria** [comment]
@Dynasto to test locally: 
* Install nodejs, I recommend [doing so with nvm](https://github.com/creationix/nvm)
* Save file and open terminal to the containing folder
* Uncomment the last portion of the code 
* Run `node clap.js`

**Comment by Dynasto** [comment]
@mcicoria thanks man! :D

**Pull request merged**
