### PR TITLE
Clap update and /no-functionality

### PR DESCRIPTION
**Pull request by Dynasto**
I updated the /clap command as requested from my roomies, and also removed the unused clap.js which i initially used to make /clap, but the command has since been moved the singlestring.js instead so clap.js can be removed.

### CODE REVIEW

**Comment by Dynasto** [comment]
I later on also added functionality for the bot to nope a song as requested by my room. It's called nockout.js (a wordplay on the existing file rockout.js) and you call the command by typing /no. I'm not sure though if the emit "do:nope" works since I can't test that specifically and there's no documentation of it as an existing command, but since "do:dope" works in the rockout.js script (which also isn't documented from what I know) I figured it would work.

**Comment by Dynasto** [comment]
Also, i tried making this two pull requests by checking in the things separately in my forked master branch, but i don't know git too well and they became the same pull request apparently. Sorry about that :/

**Comment by Moghul** [comment]
If showing interest in this branch will get some progress started, this is it.
I really want that /no functionality.

**Comment by jonasclement** [comment]
+1 for interest in the /no feature. I'd love to see some progress going on getting this implemented.

**Pull request merged**
